### ISSUE TITLE
Devise protocol for Actions publishing result of their execution

### ISSUE THREAD

**Issue by withtwoemms** [withtwoemms/actionpack#14]
**As a** Monitor of systems using `actionpack`
**I want** to know when an `Action` was `.performed`, what its outcome was, etc
**So I** can remotely follow how processing is progressing

**Comment by withtwoemms** [comment]
Ever since completion of #110, `Result` objects have a timestamp. The immutable `Result.successful` attribute was added in completion of #74. When an `Action` fails, a callback called a "reaction" is executed--delivered by #116. Though it may be desired to execute a `reaction` _independent_ of success status, executing on failure suffices for now. Can revisit in the future if needs change.

An interesting idea may be to devise a means of serializing `Result` objects so that the disposition they encapsulate can be transmitted.

As it stands, the `Result` object represents this "protocol" and there are supporting `actionpack` faculties that satisfy this ask so this issue is being closed.

**Comment by manualautomaton** [comment]
Executing a `reaction` "independent of success status" for the original `Action` could be achieved by moving [this clause](https://github.com/withtwoemms/actionpack/blob/main/actionpack/action.py#L147) to a `finally` block.
