### ISSUE TITLE
WriteBytes doesn't have an "append" mode

### ISSUE THREAD

**Issue by theradiativitycompany** [withtwoemms/actionpack#71]
**As a** user
**I want** to use the `WriteBytes` action to repeated add content to a file
**So I** accumulate results line by line

**Comment by withtwoemms** [comment]
re-opening pending user acceptance of v1.2.2a1

**Comment by withtwoemms** [comment]
user could not accept v1.2.2a1 as `WriteBytes.validate` kept running into `FileExistsError`.

**Comment by withtwoemms** [comment]
upon review, user accepts v1.2.2a2. Will  cut close and cut formal release.
